
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  email: string | null
  password: string | null
  role: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  email: string | null
  password: string | null
  role: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserCountAggregateOutputType = {
  id: number
  email: number
  password: number
  role: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UserMinAggregateInputType = {
  id?: true
  email?: true
  password?: true
  role?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  email?: true
  password?: true
  role?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type UserCountAggregateInputType = {
  id?: true
  email?: true
  password?: true
  role?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  email: string
  password: string
  role: string
  name: string
  createdAt: Date
  updatedAt: Date
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  email?: Prisma.StringFilter<"User"> | string
  password?: Prisma.StringFilter<"User"> | string
  role?: Prisma.StringFilter<"User"> | string
  name?: Prisma.StringFilter<"User"> | string
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  studentProfile?: Prisma.XOR<Prisma.StudentProfileNullableScalarRelationFilter, Prisma.StudentProfileWhereInput> | null
  trainerProfile?: Prisma.XOR<Prisma.TrainerProfileNullableScalarRelationFilter, Prisma.TrainerProfileWhereInput> | null
  examsCreated?: Prisma.ExamListRelationFilter
  results?: Prisma.ResultListRelationFilter
  answers?: Prisma.AnswerListRelationFilter
  activityLogs?: Prisma.ActivityLogListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  role?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  studentProfile?: Prisma.StudentProfileOrderByWithRelationInput
  trainerProfile?: Prisma.TrainerProfileOrderByWithRelationInput
  examsCreated?: Prisma.ExamOrderByRelationAggregateInput
  results?: Prisma.ResultOrderByRelationAggregateInput
  answers?: Prisma.AnswerOrderByRelationAggregateInput
  activityLogs?: Prisma.ActivityLogOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  password?: Prisma.StringFilter<"User"> | string
  role?: Prisma.StringFilter<"User"> | string
  name?: Prisma.StringFilter<"User"> | string
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  studentProfile?: Prisma.XOR<Prisma.StudentProfileNullableScalarRelationFilter, Prisma.StudentProfileWhereInput> | null
  trainerProfile?: Prisma.XOR<Prisma.TrainerProfileNullableScalarRelationFilter, Prisma.TrainerProfileWhereInput> | null
  examsCreated?: Prisma.ExamListRelationFilter
  results?: Prisma.ResultListRelationFilter
  answers?: Prisma.AnswerListRelationFilter
  activityLogs?: Prisma.ActivityLogListRelationFilter
}, "id" | "email">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  role?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  email?: Prisma.StringWithAggregatesFilter<"User"> | string
  password?: Prisma.StringWithAggregatesFilter<"User"> | string
  role?: Prisma.StringWithAggregatesFilter<"User"> | string
  name?: Prisma.StringWithAggregatesFilter<"User"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
}

export type UserCreateInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileCreateNestedOneWithoutUserInput
  trainerProfile?: Prisma.TrainerProfileCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamCreateNestedManyWithoutTrainerInput
  results?: Prisma.ResultCreateNestedManyWithoutStudentInput
  answers?: Prisma.AnswerCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogCreateNestedManyWithoutStudentInput
}

export type UserUncheckedCreateInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileUncheckedCreateNestedOneWithoutUserInput
  trainerProfile?: Prisma.TrainerProfileUncheckedCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamUncheckedCreateNestedManyWithoutTrainerInput
  results?: Prisma.ResultUncheckedCreateNestedManyWithoutStudentInput
  answers?: Prisma.AnswerUncheckedCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogUncheckedCreateNestedManyWithoutStudentInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUpdateOneWithoutUserNestedInput
  trainerProfile?: Prisma.TrainerProfileUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUpdateManyWithoutTrainerNestedInput
  results?: Prisma.ResultUpdateManyWithoutStudentNestedInput
  answers?: Prisma.AnswerUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUpdateManyWithoutStudentNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUncheckedUpdateOneWithoutUserNestedInput
  trainerProfile?: Prisma.TrainerProfileUncheckedUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUncheckedUpdateManyWithoutTrainerNestedInput
  results?: Prisma.ResultUncheckedUpdateManyWithoutStudentNestedInput
  answers?: Prisma.AnswerUncheckedUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUncheckedUpdateManyWithoutStudentNestedInput
}

export type UserCreateManyInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  role?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  role?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  role?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type UserCreateNestedOneWithoutStudentProfileInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutStudentProfileInput, Prisma.UserUncheckedCreateWithoutStudentProfileInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutStudentProfileInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutStudentProfileNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutStudentProfileInput, Prisma.UserUncheckedCreateWithoutStudentProfileInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutStudentProfileInput
  upsert?: Prisma.UserUpsertWithoutStudentProfileInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutStudentProfileInput, Prisma.UserUpdateWithoutStudentProfileInput>, Prisma.UserUncheckedUpdateWithoutStudentProfileInput>
}

export type UserCreateNestedOneWithoutTrainerProfileInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutTrainerProfileInput, Prisma.UserUncheckedCreateWithoutTrainerProfileInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutTrainerProfileInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutTrainerProfileNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutTrainerProfileInput, Prisma.UserUncheckedCreateWithoutTrainerProfileInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutTrainerProfileInput
  upsert?: Prisma.UserUpsertWithoutTrainerProfileInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutTrainerProfileInput, Prisma.UserUpdateWithoutTrainerProfileInput>, Prisma.UserUncheckedUpdateWithoutTrainerProfileInput>
}

export type UserCreateNestedOneWithoutExamsCreatedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutExamsCreatedInput, Prisma.UserUncheckedCreateWithoutExamsCreatedInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutExamsCreatedInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutExamsCreatedNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutExamsCreatedInput, Prisma.UserUncheckedCreateWithoutExamsCreatedInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutExamsCreatedInput
  upsert?: Prisma.UserUpsertWithoutExamsCreatedInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutExamsCreatedInput, Prisma.UserUpdateWithoutExamsCreatedInput>, Prisma.UserUncheckedUpdateWithoutExamsCreatedInput>
}

export type UserCreateNestedOneWithoutAnswersInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAnswersInput, Prisma.UserUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAnswersInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutAnswersNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAnswersInput, Prisma.UserUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAnswersInput
  upsert?: Prisma.UserUpsertWithoutAnswersInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutAnswersInput, Prisma.UserUpdateWithoutAnswersInput>, Prisma.UserUncheckedUpdateWithoutAnswersInput>
}

export type UserCreateNestedOneWithoutResultsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutResultsInput, Prisma.UserUncheckedCreateWithoutResultsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutResultsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutResultsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutResultsInput, Prisma.UserUncheckedCreateWithoutResultsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutResultsInput
  upsert?: Prisma.UserUpsertWithoutResultsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutResultsInput, Prisma.UserUpdateWithoutResultsInput>, Prisma.UserUncheckedUpdateWithoutResultsInput>
}

export type UserCreateNestedOneWithoutActivityLogsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutActivityLogsInput, Prisma.UserUncheckedCreateWithoutActivityLogsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutActivityLogsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutActivityLogsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutActivityLogsInput, Prisma.UserUncheckedCreateWithoutActivityLogsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutActivityLogsInput
  upsert?: Prisma.UserUpsertWithoutActivityLogsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutActivityLogsInput, Prisma.UserUpdateWithoutActivityLogsInput>, Prisma.UserUncheckedUpdateWithoutActivityLogsInput>
}

export type UserCreateWithoutStudentProfileInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  trainerProfile?: Prisma.TrainerProfileCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamCreateNestedManyWithoutTrainerInput
  results?: Prisma.ResultCreateNestedManyWithoutStudentInput
  answers?: Prisma.AnswerCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogCreateNestedManyWithoutStudentInput
}

export type UserUncheckedCreateWithoutStudentProfileInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  trainerProfile?: Prisma.TrainerProfileUncheckedCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamUncheckedCreateNestedManyWithoutTrainerInput
  results?: Prisma.ResultUncheckedCreateNestedManyWithoutStudentInput
  answers?: Prisma.AnswerUncheckedCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogUncheckedCreateNestedManyWithoutStudentInput
}

export type UserCreateOrConnectWithoutStudentProfileInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutStudentProfileInput, Prisma.UserUncheckedCreateWithoutStudentProfileInput>
}

export type UserUpsertWithoutStudentProfileInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutStudentProfileInput, Prisma.UserUncheckedUpdateWithoutStudentProfileInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutStudentProfileInput, Prisma.UserUncheckedCreateWithoutStudentProfileInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutStudentProfileInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutStudentProfileInput, Prisma.UserUncheckedUpdateWithoutStudentProfileInput>
}

export type UserUpdateWithoutStudentProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trainerProfile?: Prisma.TrainerProfileUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUpdateManyWithoutTrainerNestedInput
  results?: Prisma.ResultUpdateManyWithoutStudentNestedInput
  answers?: Prisma.AnswerUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUpdateManyWithoutStudentNestedInput
}

export type UserUncheckedUpdateWithoutStudentProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  trainerProfile?: Prisma.TrainerProfileUncheckedUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUncheckedUpdateManyWithoutTrainerNestedInput
  results?: Prisma.ResultUncheckedUpdateManyWithoutStudentNestedInput
  answers?: Prisma.AnswerUncheckedUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUncheckedUpdateManyWithoutStudentNestedInput
}

export type UserCreateWithoutTrainerProfileInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamCreateNestedManyWithoutTrainerInput
  results?: Prisma.ResultCreateNestedManyWithoutStudentInput
  answers?: Prisma.AnswerCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogCreateNestedManyWithoutStudentInput
}

export type UserUncheckedCreateWithoutTrainerProfileInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileUncheckedCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamUncheckedCreateNestedManyWithoutTrainerInput
  results?: Prisma.ResultUncheckedCreateNestedManyWithoutStudentInput
  answers?: Prisma.AnswerUncheckedCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogUncheckedCreateNestedManyWithoutStudentInput
}

export type UserCreateOrConnectWithoutTrainerProfileInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutTrainerProfileInput, Prisma.UserUncheckedCreateWithoutTrainerProfileInput>
}

export type UserUpsertWithoutTrainerProfileInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutTrainerProfileInput, Prisma.UserUncheckedUpdateWithoutTrainerProfileInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutTrainerProfileInput, Prisma.UserUncheckedCreateWithoutTrainerProfileInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutTrainerProfileInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutTrainerProfileInput, Prisma.UserUncheckedUpdateWithoutTrainerProfileInput>
}

export type UserUpdateWithoutTrainerProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUpdateManyWithoutTrainerNestedInput
  results?: Prisma.ResultUpdateManyWithoutStudentNestedInput
  answers?: Prisma.AnswerUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUpdateManyWithoutStudentNestedInput
}

export type UserUncheckedUpdateWithoutTrainerProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUncheckedUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUncheckedUpdateManyWithoutTrainerNestedInput
  results?: Prisma.ResultUncheckedUpdateManyWithoutStudentNestedInput
  answers?: Prisma.AnswerUncheckedUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUncheckedUpdateManyWithoutStudentNestedInput
}

export type UserCreateWithoutExamsCreatedInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileCreateNestedOneWithoutUserInput
  trainerProfile?: Prisma.TrainerProfileCreateNestedOneWithoutUserInput
  results?: Prisma.ResultCreateNestedManyWithoutStudentInput
  answers?: Prisma.AnswerCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogCreateNestedManyWithoutStudentInput
}

export type UserUncheckedCreateWithoutExamsCreatedInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileUncheckedCreateNestedOneWithoutUserInput
  trainerProfile?: Prisma.TrainerProfileUncheckedCreateNestedOneWithoutUserInput
  results?: Prisma.ResultUncheckedCreateNestedManyWithoutStudentInput
  answers?: Prisma.AnswerUncheckedCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogUncheckedCreateNestedManyWithoutStudentInput
}

export type UserCreateOrConnectWithoutExamsCreatedInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutExamsCreatedInput, Prisma.UserUncheckedCreateWithoutExamsCreatedInput>
}

export type UserUpsertWithoutExamsCreatedInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutExamsCreatedInput, Prisma.UserUncheckedUpdateWithoutExamsCreatedInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutExamsCreatedInput, Prisma.UserUncheckedCreateWithoutExamsCreatedInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutExamsCreatedInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutExamsCreatedInput, Prisma.UserUncheckedUpdateWithoutExamsCreatedInput>
}

export type UserUpdateWithoutExamsCreatedInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUpdateOneWithoutUserNestedInput
  trainerProfile?: Prisma.TrainerProfileUpdateOneWithoutUserNestedInput
  results?: Prisma.ResultUpdateManyWithoutStudentNestedInput
  answers?: Prisma.AnswerUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUpdateManyWithoutStudentNestedInput
}

export type UserUncheckedUpdateWithoutExamsCreatedInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUncheckedUpdateOneWithoutUserNestedInput
  trainerProfile?: Prisma.TrainerProfileUncheckedUpdateOneWithoutUserNestedInput
  results?: Prisma.ResultUncheckedUpdateManyWithoutStudentNestedInput
  answers?: Prisma.AnswerUncheckedUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUncheckedUpdateManyWithoutStudentNestedInput
}

export type UserCreateWithoutAnswersInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileCreateNestedOneWithoutUserInput
  trainerProfile?: Prisma.TrainerProfileCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamCreateNestedManyWithoutTrainerInput
  results?: Prisma.ResultCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogCreateNestedManyWithoutStudentInput
}

export type UserUncheckedCreateWithoutAnswersInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileUncheckedCreateNestedOneWithoutUserInput
  trainerProfile?: Prisma.TrainerProfileUncheckedCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamUncheckedCreateNestedManyWithoutTrainerInput
  results?: Prisma.ResultUncheckedCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogUncheckedCreateNestedManyWithoutStudentInput
}

export type UserCreateOrConnectWithoutAnswersInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutAnswersInput, Prisma.UserUncheckedCreateWithoutAnswersInput>
}

export type UserUpsertWithoutAnswersInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutAnswersInput, Prisma.UserUncheckedUpdateWithoutAnswersInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutAnswersInput, Prisma.UserUncheckedCreateWithoutAnswersInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutAnswersInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutAnswersInput, Prisma.UserUncheckedUpdateWithoutAnswersInput>
}

export type UserUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUpdateOneWithoutUserNestedInput
  trainerProfile?: Prisma.TrainerProfileUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUpdateManyWithoutTrainerNestedInput
  results?: Prisma.ResultUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUpdateManyWithoutStudentNestedInput
}

export type UserUncheckedUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUncheckedUpdateOneWithoutUserNestedInput
  trainerProfile?: Prisma.TrainerProfileUncheckedUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUncheckedUpdateManyWithoutTrainerNestedInput
  results?: Prisma.ResultUncheckedUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUncheckedUpdateManyWithoutStudentNestedInput
}

export type UserCreateWithoutResultsInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileCreateNestedOneWithoutUserInput
  trainerProfile?: Prisma.TrainerProfileCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamCreateNestedManyWithoutTrainerInput
  answers?: Prisma.AnswerCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogCreateNestedManyWithoutStudentInput
}

export type UserUncheckedCreateWithoutResultsInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileUncheckedCreateNestedOneWithoutUserInput
  trainerProfile?: Prisma.TrainerProfileUncheckedCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamUncheckedCreateNestedManyWithoutTrainerInput
  answers?: Prisma.AnswerUncheckedCreateNestedManyWithoutStudentInput
  activityLogs?: Prisma.ActivityLogUncheckedCreateNestedManyWithoutStudentInput
}

export type UserCreateOrConnectWithoutResultsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutResultsInput, Prisma.UserUncheckedCreateWithoutResultsInput>
}

export type UserUpsertWithoutResultsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutResultsInput, Prisma.UserUncheckedUpdateWithoutResultsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutResultsInput, Prisma.UserUncheckedCreateWithoutResultsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutResultsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutResultsInput, Prisma.UserUncheckedUpdateWithoutResultsInput>
}

export type UserUpdateWithoutResultsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUpdateOneWithoutUserNestedInput
  trainerProfile?: Prisma.TrainerProfileUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUpdateManyWithoutTrainerNestedInput
  answers?: Prisma.AnswerUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUpdateManyWithoutStudentNestedInput
}

export type UserUncheckedUpdateWithoutResultsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUncheckedUpdateOneWithoutUserNestedInput
  trainerProfile?: Prisma.TrainerProfileUncheckedUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUncheckedUpdateManyWithoutTrainerNestedInput
  answers?: Prisma.AnswerUncheckedUpdateManyWithoutStudentNestedInput
  activityLogs?: Prisma.ActivityLogUncheckedUpdateManyWithoutStudentNestedInput
}

export type UserCreateWithoutActivityLogsInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileCreateNestedOneWithoutUserInput
  trainerProfile?: Prisma.TrainerProfileCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamCreateNestedManyWithoutTrainerInput
  results?: Prisma.ResultCreateNestedManyWithoutStudentInput
  answers?: Prisma.AnswerCreateNestedManyWithoutStudentInput
}

export type UserUncheckedCreateWithoutActivityLogsInput = {
  id?: string
  email: string
  password: string
  role?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  studentProfile?: Prisma.StudentProfileUncheckedCreateNestedOneWithoutUserInput
  trainerProfile?: Prisma.TrainerProfileUncheckedCreateNestedOneWithoutUserInput
  examsCreated?: Prisma.ExamUncheckedCreateNestedManyWithoutTrainerInput
  results?: Prisma.ResultUncheckedCreateNestedManyWithoutStudentInput
  answers?: Prisma.AnswerUncheckedCreateNestedManyWithoutStudentInput
}

export type UserCreateOrConnectWithoutActivityLogsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutActivityLogsInput, Prisma.UserUncheckedCreateWithoutActivityLogsInput>
}

export type UserUpsertWithoutActivityLogsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutActivityLogsInput, Prisma.UserUncheckedUpdateWithoutActivityLogsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutActivityLogsInput, Prisma.UserUncheckedCreateWithoutActivityLogsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutActivityLogsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutActivityLogsInput, Prisma.UserUncheckedUpdateWithoutActivityLogsInput>
}

export type UserUpdateWithoutActivityLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUpdateOneWithoutUserNestedInput
  trainerProfile?: Prisma.TrainerProfileUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUpdateManyWithoutTrainerNestedInput
  results?: Prisma.ResultUpdateManyWithoutStudentNestedInput
  answers?: Prisma.AnswerUpdateManyWithoutStudentNestedInput
}

export type UserUncheckedUpdateWithoutActivityLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studentProfile?: Prisma.StudentProfileUncheckedUpdateOneWithoutUserNestedInput
  trainerProfile?: Prisma.TrainerProfileUncheckedUpdateOneWithoutUserNestedInput
  examsCreated?: Prisma.ExamUncheckedUpdateManyWithoutTrainerNestedInput
  results?: Prisma.ResultUncheckedUpdateManyWithoutStudentNestedInput
  answers?: Prisma.AnswerUncheckedUpdateManyWithoutStudentNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  examsCreated: number
  results: number
  answers: number
  activityLogs: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  examsCreated?: boolean | UserCountOutputTypeCountExamsCreatedArgs
  results?: boolean | UserCountOutputTypeCountResultsArgs
  answers?: boolean | UserCountOutputTypeCountAnswersArgs
  activityLogs?: boolean | UserCountOutputTypeCountActivityLogsArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountExamsCreatedArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExamWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountResultsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ResultWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountAnswersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AnswerWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountActivityLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActivityLogWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  password?: boolean
  role?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  studentProfile?: boolean | Prisma.User$studentProfileArgs<ExtArgs>
  trainerProfile?: boolean | Prisma.User$trainerProfileArgs<ExtArgs>
  examsCreated?: boolean | Prisma.User$examsCreatedArgs<ExtArgs>
  results?: boolean | Prisma.User$resultsArgs<ExtArgs>
  answers?: boolean | Prisma.User$answersArgs<ExtArgs>
  activityLogs?: boolean | Prisma.User$activityLogsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  password?: boolean
  role?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  password?: boolean
  role?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  email?: boolean
  password?: boolean
  role?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "password" | "role" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  studentProfile?: boolean | Prisma.User$studentProfileArgs<ExtArgs>
  trainerProfile?: boolean | Prisma.User$trainerProfileArgs<ExtArgs>
  examsCreated?: boolean | Prisma.User$examsCreatedArgs<ExtArgs>
  results?: boolean | Prisma.User$resultsArgs<ExtArgs>
  answers?: boolean | Prisma.User$answersArgs<ExtArgs>
  activityLogs?: boolean | Prisma.User$activityLogsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    studentProfile: Prisma.$StudentProfilePayload<ExtArgs> | null
    trainerProfile: Prisma.$TrainerProfilePayload<ExtArgs> | null
    examsCreated: Prisma.$ExamPayload<ExtArgs>[]
    results: Prisma.$ResultPayload<ExtArgs>[]
    answers: Prisma.$AnswerPayload<ExtArgs>[]
    activityLogs: Prisma.$ActivityLogPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    password: string
    role: string
    name: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  studentProfile<T extends Prisma.User$studentProfileArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$studentProfileArgs<ExtArgs>>): Prisma.Prisma__StudentProfileClient<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  trainerProfile<T extends Prisma.User$trainerProfileArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$trainerProfileArgs<ExtArgs>>): Prisma.Prisma__TrainerProfileClient<runtime.Types.Result.GetResult<Prisma.$TrainerProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  examsCreated<T extends Prisma.User$examsCreatedArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$examsCreatedArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExamPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  results<T extends Prisma.User$resultsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$resultsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  answers<T extends Prisma.User$answersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$answersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  activityLogs<T extends Prisma.User$activityLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$activityLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActivityLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly password: Prisma.FieldRef<"User", 'String'>
  readonly role: Prisma.FieldRef<"User", 'String'>
  readonly name: Prisma.FieldRef<"User", 'String'>
  readonly createdAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"User", 'DateTime'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.studentProfile
 */
export type User$studentProfileArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
  where?: Prisma.StudentProfileWhereInput
}

/**
 * User.trainerProfile
 */
export type User$trainerProfileArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainerProfile
   */
  select?: Prisma.TrainerProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainerProfile
   */
  omit?: Prisma.TrainerProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainerProfileInclude<ExtArgs> | null
  where?: Prisma.TrainerProfileWhereInput
}

/**
 * User.examsCreated
 */
export type User$examsCreatedArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exam
   */
  select?: Prisma.ExamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exam
   */
  omit?: Prisma.ExamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExamInclude<ExtArgs> | null
  where?: Prisma.ExamWhereInput
  orderBy?: Prisma.ExamOrderByWithRelationInput | Prisma.ExamOrderByWithRelationInput[]
  cursor?: Prisma.ExamWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExamScalarFieldEnum | Prisma.ExamScalarFieldEnum[]
}

/**
 * User.results
 */
export type User$resultsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Result
   */
  select?: Prisma.ResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Result
   */
  omit?: Prisma.ResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResultInclude<ExtArgs> | null
  where?: Prisma.ResultWhereInput
  orderBy?: Prisma.ResultOrderByWithRelationInput | Prisma.ResultOrderByWithRelationInput[]
  cursor?: Prisma.ResultWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ResultScalarFieldEnum | Prisma.ResultScalarFieldEnum[]
}

/**
 * User.answers
 */
export type User$answersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Answer
   */
  select?: Prisma.AnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Answer
   */
  omit?: Prisma.AnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnswerInclude<ExtArgs> | null
  where?: Prisma.AnswerWhereInput
  orderBy?: Prisma.AnswerOrderByWithRelationInput | Prisma.AnswerOrderByWithRelationInput[]
  cursor?: Prisma.AnswerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AnswerScalarFieldEnum | Prisma.AnswerScalarFieldEnum[]
}

/**
 * User.activityLogs
 */
export type User$activityLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLog
   */
  select?: Prisma.ActivityLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLog
   */
  omit?: Prisma.ActivityLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogInclude<ExtArgs> | null
  where?: Prisma.ActivityLogWhereInput
  orderBy?: Prisma.ActivityLogOrderByWithRelationInput | Prisma.ActivityLogOrderByWithRelationInput[]
  cursor?: Prisma.ActivityLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ActivityLogScalarFieldEnum | Prisma.ActivityLogScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
